version: '3.4'

services:
  whatsappchangelog:
    image: whatsappchangelog
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
